spring:
  application:
    name: order
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: secretpassword123
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8080
